[package]
name = "mi-api"
version = "0.0.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
axum = { version = "0.6", features = ["macros", "http2"] }
axum-auth = "0.4"
axum-macros = "0.3"
rand_chacha = "0.3"
dotenvy = "0.15"
hyper = { version = "0.14", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.23", features = ["full"] }
tower = "0.4"
once_cell = "1.17"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sqlx = { version = "0.6", features = [
    "default",
    "runtime-tokio-rustls",
    "postgres",
] }
reqwest = "0.11"
tower-cookies = "0.9"
mi-db = { path = "../mi-db", version = "0.0.0"}
mi-osu-api = { path = "../mi-osu-api", version = "0.0.0"}
parking_lot = "0.12"
validator = { version = "0.16", features = ["derive"] }

bb8 = "0.8"
bb8-redis = "0.12"
redis = { version = "0.22", features = ["tokio-comp"] }
