services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres-mi
    ports:
      - "5432:5432"
    profiles:
      - all
      - postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER:-mi-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mi-dev}
      POSTGRES_DB: ${POSTGRES_DB:-mapper-influence-dev}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
  redis:
    image: redis:7.0.5-alpine
    container_name: redis-mi
    ports:
      - "6379:6379"
    profiles:
      - all
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  agent:
    image: mi-grafana-agent
    container_name: agent-mi
    ports:
      - "4317:4317"
    profiles:
      - all
      - agent
    environment:
      TEMPO_API_KEY: ${TEMPO_API_KEY}
      TEMPO_ENDPOINT: ${TEMPO_ENDPOINT}
      TEMPO_USERNAME: ${TEMPO_USERNAME}
      PORT: ${PORT}
