FROM debian:bullseye-slim

ARG TEMPO_ENDPOINT
ARG TEMPO_USERNAME
ARG TEMPO_API_KEY
ARG PORT

ENV TEMPO_ENDPOINT=${TEMPO_ENDPOINT}
ENV TEMPO_USERNAME=${TEMPO_USERNAME}
ENV TEMPO_API_KEY=${TEMPO_API_KEY}

RUN apt-get update && apt-get install -y curl unzip

RUN curl -O -L "https://github.com/grafana/agent/releases/download/v0.32.1/grafana-agent-linux-amd64.zip"

RUN unzip "grafana-agent-linux-amd64.zip"

RUN chmod a+x "grafana-agent-linux-amd64"

COPY ./grafana-agent-config.yaml /etc/agent/agent.yaml

EXPOSE ${PORT}

CMD ./grafana-agent-linux-amd64 --config.file=/etc/agent/agent.yaml -config.expand-env -server.grpc.address=0.0.0.0:$PORT
