traces:
  configs:
  - name: default
    remote_write:
      - endpoint: ${TEMPO_ENDPOINT}
        basic_auth:
          username: ${TEMPO_USERNAME}
          password: ${TEMPO_API_KEY}
    receivers:
      otlp:
        protocols:
          grpc:
