[package]
name = "mi-db"
version = "0.0.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bb8 = "0.8"
bb8-redis = "0.12"
redis = { version = "0.22", features = ["tokio-comp"] }
sqlx = { version = "0.6", features = [
    "default",
    "runtime-tokio-rustls",
    "postgres",
] }
tracing = "0.1"
thiserror = "1.0"

[build-dependencies]
sqlx = { version = "0.6", features = [
    "default",
    "runtime-tokio-rustls",
    "postgres",
    "offline",
] }
tokio = { version = "1.25", features = ["macros"] }
dotenvy = "0.15"

[dev-dependencies]
once_cell = "1.17"
futures = "0.3"
tokio = { version = "1.25", features = ["macros"] }

[features]
db-tests = []
