[package]
name = "mi-db"
version = "0.0.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6", features = [
    "default",
    "runtime-tokio-rustls",
    "postgres",
] }
tracing = "0.1"
thiserror = "1.0"

[build-dependencies]
sqlx = { version = "0.6", features = [
    "default",
    "runtime-tokio-rustls",
    "postgres",
    "offline",
] }
tokio = { version = "1.21", features = ["macros"] }
dotenvy = "0.15"

[features]
db-tests = []
