[package]
name = "mi-db"
version = "0.0.0"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bb8 = "0.8"
bb8-redis = "0.12"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
redis = { version = "0.22", features = ["tokio-comp"] }
sqlx = { version = "0.6", features = [
    "default",
    "runtime-tokio-rustls",
    "postgres",
    "json",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
tokio = { version = "1.22", features = ["macros"] }
utoipa = { version = "3.1", features = ["axum_extras"] }
mi-osu-api = { path = "../mi-osu-api", version = "0.0.0" }

[build-dependencies]
dotenvy = "0.15"
sqlx = { version = "0.6", features = [
    "default",
    "runtime-tokio-rustls",
    "postgres",
    "offline",
] }

tokio = { version = "1.22", features = ["macros"] }

[dev-dependencies]
futures = "0.3"
once_cell = "1.16"
tokio = { version = "1.22", features = ["macros"] }

[features]
db-tests = []
